service: invoicely

provider:
  name: aws
  runtime: go1.x
  region: eu-west-1
  environment:
    REGION: "eu-west-1"
  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
    Resource: "arn:aws:dynamodb:eu-west-1:*:table/*"

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  create-client:
    handler: bin/clients
    environment:
      DB_TABLE: Clients
    events:
      - http:
          path: clients
          method: post
          cors: true

  fetch-clients:
    handler: bin/clients
    environment:
      DB_TABLE: Clients
    events:
      - http:
          path: clients
          method: get
          cors: true

  fetch-client:
    handler: bin/clients
    environment:
      DB_TABLE: Clients
    events:
      - http:
          path: clients/{id}
          method: get
          cors: true

  create-sprint:
    handler: bin/sprints
    environment:
      DB_TABLE: Sprints
    events:
      - http:
          path: sprints
          method: post
          cors: true
  
  fetch-sprints:
    handler: bin/sprints
    environment:
      DB_TABLE: Sprints
    events:
      - http:
          path: sprints
          method: get
          cors: true

  fetch-sprint:
    handler: bin/sprints
    environment:
      DB_TABLE: Sprints
    events:
      - http:
          path: sprints/{id}
          method: get
          cors: true
  
  create-item:
    handler: bin/create-item
    environment:
      DB_NAME: Item
    events:
      - http:
          path: items
          method: post
          cors: true

  fetch-items:
    handler: bin/fetch-item
    environment:
      DB_NAME: Item
    events:
      - http:
          path: items
          method: get
          cors: true

  fetch-item:
    handler: bin/fetch-items
    environment:
      DB_NAME: Item
    events:
      - http:
          path: items/{id}
          method: get
          cors: true

resources:
  Resources:
    clientsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Clients
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    sprintsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Sprints
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    itemsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Items
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1